export const FETCH_USER_REQUEST="FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESSFULL="FETCH_USER_SUCCESSFULL";
export const FETCH_USER_FAILURE="FETCH_USER_FAILURE"
export const FETCH_SELECTED_ID="FETCH_SELECTED_ID"